import { addUser } from './db';
import { countries } from './countries';

const handles = [
  "@MindfulWanderer",
  "@MusicMaven",
  "@AtomicAstral",
  "@NatureLover",
  "@NitroNebula",
  "@GenerousGiver",
  "@LovingHeart",
  "@SereneSerenade",
  "@EtherealEnigma",
  "@NebulaNova",
  "@ShadowSorcerer",
  "@StellarSpellbinder",
  "@TrueBeliever",
  "@StellarSerenity",
  "@CalmOasis",
  "@EnchantingEssence",
  "@QuantumQuester",
  "@GhostGlider",
  "@InfiniteInspiration",
  "@CelestialOasis",
  "@ElectricEcho",
  "@StarrySidereal",
  "@MidnightMarauder",
  "@FantabulousFantasy",
  "@TechnoTinker",
  "@CompassionateSoul",
  "@MindfulSerenity",
  "@StarlitSpecter",
  "@LunaLovegood",
  "@SparkleGuru",
  "@BlazeByte",
  "@LavenderDreams",
  "@WanderlustSoul",
  "@PhoenixFire",
  "@SereneSpell",
  "@PhoenixRising",
  "@WanderlustAdventures",
  "@PixelatedProdigy",
  "@NebulousNomad",
  "@AstralAmity",
  "@MistySerenity",
  "@SereneSensation",
  "@WhispersOfTranquility",
  "@CosmicCohort",
  "@DreamyDusk",
  "@NebulaNurturer",
  "@LuminousSerenade",
  "@StellarSentinel",
  "@NebulaNomad",
  "@MovieMagic",
  "@LunaLullaby",
  "@SmilingSage",
  "@MidnightMercenary",
  "@ChampionChaser",
  "@StarlitStargazer",
  "@SereneSilhouette",
  "@SilkenSerenity",
  "@HappyTraveler",
  "@DreamyDynamo",
  "@GentleSpirit",
  "@SerenityGlow",
  "@CosmicCreator",
  "@MusicMadness",
  "@CelestialSolace",
  "@StellarSymphony",
  "@SerendipitySinger",
  "@HyperHawk",
  "@PixelPassion",
  "@NebulaNymph",
  "@EnchantingEndeavor",
  "@RadiantRipple",
  "@StarryEyes",
  "@EnchantingEcho",
  "@BlossomCascade",
  "@FabledFlames",
  "@EmpoweredSpirit",
  "@EnchantedEphemeral",
  "@StellarSparkler",
  "@NeonNyx",
  "@StarrySeeker",
  "@InspireBright",
  "@TechJunkie",
  "@CosmicVoyager",
  "@Dreamweaver",
  "@MysticMoon",
  "@StarlightWhisper",
  "@CelestialDreamer",
  "@HarmonyHeart",
  "@NebulaNavigator",
  "@EtherealDream",
  "@StellarSoul",
  "@LuminousHeart",
  "@SerenitySpirit",
  "@WhisperingWanderer",
  "@CelestialTraveler",
  "@MysticMuse",
  "@StarlitWhisper",
  "@CosmicHarmony",
  "@DreamChaser",
  "@HarmonySoul",
  "@NebulaSeeker",
  "@StarryNavigator",
];

const generateRandomScore = () => Math.floor(Math.random() * 1000);

const populateDB = async () => {
  for (let i = 0; i < handles.length; i++) { // Creating 100 fake users
    const userId = handles[i];
    const country = countries[Math.floor(Math.random() * countries.length)];
    const coins = generateRandomScore();
    await addUser({ userid: userId, country, coins });
  }
  console.log('Database populated with fake users');
};

export default populateDB;
